import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Aos from 'aos';
import {useEffect} from 'react';
import 'aos/dist/aos.css';

export default function Home() {
    useEffect(() =>
    {
        Aos.init({
           duration: 1200,
           once: true,
           mirror: true,
           disable: 'phone',
        })
    })
  return (
    <div className={styles.container}>
      <Head>
        <title>Anthony Doan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light" />
      </Head>
      <body className="font-body text-white bg-[url('/Background_poker.jpg')] pb-12">
        <header className="py-6">
            <div className="container flex flex-col sm:flex-row justify-between items-center mx-auto px-8 md:px-14 md:flex lg:px-24 w-full">
                <div className="text-blue-400 text-3xl lg:text-4xl" data-aos='fade-right' >ANTHONY.DOAN</div>
                    <div className="mt-2 flex space-x-12 items-center text-xl" id="menu" data-aos='fade-left'>
                        <div>
                            <Link href="/"><a className="p-4 text-blue-400 hover:font-bold">Home</a></Link>
                            <Link href="/Proj"><a className="p-4 hover:font-bold text-blue-400">Projects</a></Link>
                            <Link href="/Contact"><a className="p-4 hover:font-bold text-blue-400 underline">Contact</a></Link>
                        </div>
                    </div>
            </div>
            <h1 className="mt-40 text-4xl text-center">
                Coming Soon...
            </h1>
        </header>
            
       </body>
    </div>
  )
}
