import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { AiOutlineGithub, AiOutlineFilePdf, AiFillLinkedin, AiFillMail } from 'react-icons/ai';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anthony Doan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light" />
      </Head>
      <body className="text-white bg-[url('/Background_poker.jpg')] pb-12">
        <header className="py-6">
            <div className="container flex flex-col sm:flex-row justify-between items-center mx-auto px-8 md:px-14 md:flex lg:px-24 w-full">
                <div className="text-blue-400 font-body text-3xl lg:text-4xl">ANTHONY.DOAN</div>
                    <div className="mt-2 flex space-x-12 items-center text-xl" id="menu">
                        <div>
                            <Link href="/"><a className="p-4 text-blue-400 hover:font-bold underline">Home</a></Link>
                            <Link href="/Proj"><a className="p-4 hover:font-bold text-blue-400">Projects</a></Link>
                            <Link href="/Skills"><a className="p-4 hover:font-bold text-blue-400">Skills</a></Link>
                        </div>
                    </div>
            </div>
            <div className="sm:py-24 md:py-32 text-blue-400 text-xl sm:ml-4 md:ml-8 md:mr-34 lg:mr-92">
                <div className="continer justify-center items-center mx-auto px-8 sm:px-auto md:px-14 md:flex lg:px-24 lg:flex w-full">
                    <img src='https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light'/>  
                    <p className="mt-10 ml-2">
                        Welcome! My name is Anthony, a 22 years old computer engineering student at Cal Poly Pomona. I enjoy creating full-stack applications and am always looking for ways to improve my programming skills. 
                    </p>
                </div>
            <div className="socials flex flex-nowrap pt-8 space-x-8 justify-start px-12 md:px-24 mt-4">
                <div className="icons">
                    <a href="https://github.com/antdoan123">
                        <AiOutlineGithub size={"36"}/>
                    </a>
                </div>
                <div className="icons">
                    <a href="https://www.linkedin.com/in/anthony-doan-9176a21b8/">
                        <AiFillLinkedin size={"36"}/>
                    </a>
                </div>
                <div className="icons">
                    <a href="mailto:antdoan1999@gmail.com">
                        <AiFillMail size={"36"}/>
                    </a>
                </div>
                <div className="icons">
                    <a href="/Resume.pdf">
                        <AiOutlineFilePdf size={"36"}/>
                    </a>
                </div>
            </div>
            </div>
        </header>
       </body>

    </div>
  )
}
