import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/Link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="text-white bg-black pb-12">
        <header className="py-6">
            <div className="container flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">
                <div className="text-blue-700 font-body sm:text-2xl md:text-3xl lg:text-4xl">ANTHONY.DOAN</div>
                    <div className="flex space-x-12 items-center text-xl" id="menu">
                        <div>
                            <Link href="/"><a className="p-4 text-blue-600 hover:font-bold">Home</a></Link>
                            <Link href="/Proj"><a className="p-4 hover:font-bold text-blue-600 underline">Projects</a></Link>
                            <Link href="/Skills"><a className="p-4 hover:font-bold text-blue-600">Skills</a></Link>
                        </div>
                    </div>
            </div>
            <section className="md:h-full flex items-center text-gray-300">
        <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-wrap -m-4">
                <div className="p-4 sm:w-1/2 lg:w-1/3">
                    <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                       
                        <div className="p-6 hover:bg-blue-700 hover:text-white transition duration-300 ease-in">
                            <h2 className="text-base font-medium text-blue-300 mb-1">C#/ .NET/ LocalDB</h2>
                            <h1 className="text-2xl font-semibold mb-3">Resteraunt Locator</h1>
                            <p className="leading-relaxed mb-3">A full-stack desktop application that allows users to find a nearby resteruant based on their preferences using Yelp&apos;s API.
                                                            Users will also be prompt to create an account which allows them to have their own unique profile and each account is stored in
                                                            a local databased. The users will also have accessed to their own dashboard. </p>
                            <div className="flex items-center flex-wrap ">
                                <a className="text-blue-300 inline-flex items-center md:mb-2 lg:mb-0">GitHub
                                    <svg className="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"
                                        fill="none" strokeLinecap="round" strokeLinejoin="round">
                                        <path d="M5 12h14"></path>
                                        <path d="M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                                <div className="icons">
                                    <a href="https://github.com/antdoan123">
                                        <span className="text-gray-300 inline-flex items-center leading-none text-sm">
                                            <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="36" width="36" 
                                            xmlns="http://www.w3.org/2000/svg"><path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9a127.5 127.5 0 0 1 38.1 91v112.5c.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="p-4 sm:w-1/2 lg:w-1/3">
                    <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                      
                        <div className="p-6 hover:bg-blue-700 hover:text-white transition duration-300 ease-in">
                            <h2 className="text-base font-medium text-blue-300 mb-1">C / PICK-IT4</h2>
                            <h1 className="text-2xl font-semibold mb-3">Traffic Light Simulator</h1>
                            <p className="leading-relaxed mb-3">Incorporated a screen that display a traffic light simulation as well as a switch that activates a crosswalk timer 
                                                            using seven-segment display. A photo sensor is used to sense whether the traffic controller is operating in 
                                                            Day Mode or Night Mode. This is all processed using a PIC18F4620.</p>
                            <div className="flex items-center flex-wrap ">
                                <a className="text-blue-300 inline-flex items-center md:mb-2 lg:mb-0">GitHub
                                    <svg className="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"
                                        fill="none" strokeLinecap="round" strokeLinejoin="round">
                                        <path d="M5 12h14"></path>
                                        <path d="M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                                <div className="icons">
                                    <a href="https://github.com/antdoan123">
                                        <span className="text-gray-300 inline-flex items-center leading-none text-sm">
                                            <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="36" width="36" 
                                            xmlns="http://www.w3.org/2000/svg"><path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9a127.5 127.5 0 0 1 38.1 91v112.5c.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="p-4 sm:w-1/2 lg:w-1/3">
                    <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                        
                        <div className="p-6 hover:bg-blue-700 hover:text-white transition duration-300 ease-in">
                            <h2 className="text-base font-medium text-blue-300 mb-1">C# / .NET</h2>
                            <h1 className="text-2xl font-semibold mb-3">Wallpaper Taskbar</h1>
                            <p className="leading-relaxed mb-3">A user interface for desktop backgrounds that displays the current time and date
                                                            along with a schedule of the user&apos;s classes that the user stores in a local databased.
                                                            By clicking on the class name, it will redirect them directly to the zoom link. The user may
                                                            also change the orientation of the GUI. </p>
                            <div className="flex items-center flex-wrap ">
                                <a className="text-blue-300 inline-flex items-center md:mb-2 lg:mb-0">GitHub
                                    <svg className="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"
                                        fill="none" strokeLinecap="round" strokeLinejoin="round">
                                        <path d="M5 12h14"></path>
                                        <path d="M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                                <div className="icons">
                                    <a href="https://github.com/antdoan123">
                                        <span clasNames="text-gray-300 inline-flex items-center leading-none text-sm">
                                            <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="36" width="36" 
                                            xmlns="http://www.w3.org/2000/svg"><path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9a127.5 127.5 0 0 1 38.1 91v112.5c.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="p-4 sm:w-1/2 lg:w-1/3">
                    <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                      
                        <div className="p-6 hover:bg-blue-700 hover:text-white transition duration-300 ease-in">
                            <h2 className="text-base font-medium text-blue-300 mb-1">TailwindCSS / Next.JS</h2>
                            <h1 className="text-2xl font-semibold mb-3">This Website</h1>
                            <p className="leading-relaxed mb-3">This website was build using TailwindCSS and Next.JS. Flexbox are used to create 
                                                            cards that stores informations. Basic TailwindCSS animation are used to make the
                                                            site more responsive. Next.JS is used to create a server-side rendering website as well
                                                            as providing better structures for the codes.</p>
                            <div className="flex items-center flex-wrap ">
                                <a className="text-blue-300 inline-flex items-center md:mb-2 lg:mb-0">GitHub
                                    <svg className="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"
                                        fill="none" strokeLinecap="round" strokeLinejoin="round">
                                        <path d="M5 12h14"></path>
                                        <path d="M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                                <div className="icons">
                                    <a href="https://github.com/antdoan123">
                                        <span className="text-gray-300 inline-flex items-center leading-none text-sm">
                                            <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="36" width="36" 
                                            xmlns="http://www.w3.org/2000/svg"><path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9a127.5 127.5 0 0 1 38.1 91v112.5c.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z"></path>
                                            </svg>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
        </header>
       </body>

    </div>
  )
}
