import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Scroll() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anthony Doan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light" />
      </Head>
      <body className="font-body h-screen text-white bg-[url('/Background_poker.jpg')] pb-12 ease-in" id="Scroll">
        <header className="py-6">
            
        </header>
            
       </body>
    </div>
  )
}
