import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {SiPython, SiDotnet, SiCplusplus, SiCsharp, SiTailwindcss, SiReact, SiHtml5, SiNextdotjs, SiCss3} from 'react-icons/si'
import Aos from 'aos';
import {useEffect} from 'react';
import 'aos/dist/aos.css';

export default function Scroll() {
    useEffect(() =>
    {
        Aos.init({
           duration: 1200,
           once: false,
           mirror: true,
           disable: 'phone',
        })
    })
  return (
    <div className={styles.container}>
      <Head>
        <title>Anthony Doan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light" />
      </Head>
      <body className="font-body h-screen text-white bg-[url('/Background_poker.jpg')] pb-12" >
        <div className="max-w-4xl mx-auto justify-center py-12" id="tech">
            <p className="text-blue-400 text-center text-4xl md:text-2x1 pt-4 font-bold" data-aos="fade-down">
                Techs I know
            </p>
        </div>
            <div className="flex flex-wrap justify-center pt-2" data-aos="fade-left">
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiPython color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">Python</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52" data-aos="fade-right">
                    <SiCplusplus color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">C Plus Plus</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiCsharp color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">C Sharp</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiDotnet color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">.NET</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiTailwindcss color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">Tailwind CSS</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiHtml5 color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">HTML5</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiCss3 color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">CSS3</p>
                </div>                     
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiReact color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">ReactJS</p>
                </div>
                <div className="icons flex flex-col w-40 p-10 m-6 overflow=hidden shadow-2xl rounded-xl sm:w-52">
                    <SiNextdotjs color="2196f3" className="mx-auto" size={"36"}/>
                    <p className="text-blue-400 mt-6 text-xl sm:text-2xl font-semibold text-center">Next.JS</p>
                </div>
            </div>
        <div className="flex justify-center mt-4" data-aos="fade-left">
            <footer className="text-blue-400 mb-4 text-xl sm:text-2xl font-semibold text-center">
                Website created by <a className="icons hover:underline" href="https://www.antdoan.dev">Anthony Doan</a>
            </footer>
        </div>
      </body>
    </div>
  )
}
