import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anthony Doan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Happy&eyebrowType=Default&mouthType=Default&skinColor=Light" />
      </Head>
      <body className="font-body h-screen text-white bg-[url('/Background_poker.jpg')] pb-12">
        <header className="py-6">
            <div className="container flex flex-col sm:flex-row justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">
                <div className="text-blue-400 font-body sm:text-2xl md:text-3xl lg:text-4xl">ANTHONY.DOAN</div>
                    <div className="mt-2 flex space-x-12 items-center text-xl" id="menu">
                        <div>
                            <Link href="/"><a className="p-4 text-blue-400 hover:font-bold">Home</a></Link>
                            <Link href="/Proj"><a className="p-4 hover:font-bold text-blue-400">Projects</a></Link>
                            <Link href="/Skills"><a className="p-4 hover:font-bold text-blue-400 underline">Skills</a></Link>
                        </div>
                    </div>
            </div>
            <h1 className="mt-40 text-4xl text-center">
                Coming Soon...
            </h1>
        </header>
            
       </body>
    </div>
  )
}
