import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/Link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="h-screen text-white bg-black pb-12">
        <header className="py-6">
            <div className="container flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">
                <div className="text-blue-700 font-body sm:text-2xl md:text-3xl lg:text-4xl">ANTHONY.DOAN</div>
                    <div className="flex space-x-12 items-center text-xl" id="menu">
                        <div>
                            <Link href="/"><a className="p-4 text-blue-600 hover:font-bold">Home</a></Link>
                            <Link href="/Proj"><a className="p-4 hover:font-bold text-blue-600">Projects</a></Link>
                            <Link href="/Skills"><a className="p-4 hover:font-bold text-blue-600 underline">Skills</a></Link>
                        </div>
                    </div>
            </div>
        </header>
            
       </body>
    </div>
  )
}
